name: CI

on: push

jobs:
  build:
    uses: danielkjellid/github-actions/.github/workflows/node.yaml@main
    with:
      cmd: npm run build:production

  prettier:
    uses: danielkjellid/github-actions/.github/workflows/node.yaml@main
    with:
      cmd: npm run prettier:check

  eslint:
    uses: danielkjellid/github-actions/.github/workflows/node.yaml@main
    with:
      cmd: npm run eslint:check

  ci-done:
    # Gather job which deploy workflow can wait on.
    name: CI done
    needs:
      - build
      - prettier
      - eslint
    runs-on: ubuntu-20.04
    steps:
      - run: echo "CI done!"
